name: Pull request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  continuous-integration:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
